## Step 1: Create Dummy Dataset

In [2]:
import pandas as pd
import numpy as np

# Create a dummy dataset
data = {
    "Patient_ID": ["P1","P2","P3","P4","P5","P6","P7","P8","P9","P10"],
    "Age": [25, 30, np.nan, 22, 40, np.nan, 29, 31, 28, np.nan],
    "Blood_Pressure": [120, 130, 125, np.nan, 140, 135, np.nan, 128, 132, 130],
    "Gender": ["M", "F", "F", "M", np.nan, "F", "M", "M", np.nan, "F"],
    "Cholesterol": [200, 220, 210, 205, np.nan, 215, 225, np.nan, 230, 210]
}

df = pd.DataFrame(data)

print("Original Dataset:\n", df)

Original Dataset:
   Patient_ID   Age  Blood_Pressure Gender  Cholesterol
0         P1  25.0           120.0      M        200.0
1         P2  30.0           130.0      F        220.0
2         P3   NaN           125.0      F        210.0
3         P4  22.0             NaN      M        205.0
4         P5  40.0           140.0    NaN          NaN
5         P6   NaN           135.0      F        215.0
6         P7  29.0             NaN      M        225.0
7         P8  31.0           128.0      M          NaN
8         P9  28.0           132.0    NaN        230.0
9        P10   NaN           130.0      F        210.0

## Step 2: Inspect Dataset

In [3]:
# Check data types and missing values
df.info()

# Get statistical summary of numerical columns
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Patient_ID      10 non-null     object
 1   Age             7 non-null      float64
 2   Blood_Pressure  8 non-null      float64
 3   Gender          8 non-null      object
 4   Cholesterol     8 non-null      float64
dtypes: float64(3), object(2)
memory usage: 532.0+ bytes

             Age  Blood_Pressure  Cholesterol
count   7.000000        8.000000     8.000000
mean   29.285714      130.000000   214.375000
std     5.648430        6.071008    10.155048
min    22.000000      120.000000   200.000000
25%    26.500000      127.250000   208.750000
50%    29.000000      130.000000   212.500000
75%    30.500000      132.750000   221.250000
max    40.000000      140.000000   230.000000

## Step 3: Mean Imputation

In [4]:
# Make a copy of the dataset
df_mean = df.copy()

# Apply mean imputation for numerical columns
df_mean.fillna({
    "Age": df["Age"].mean(),
    "Blood_Pressure": df["Blood_Pressure"].mean(),
    "Cholesterol": df["Cholesterol"].mean()
}, inplace=True)

print("After Mean Imputation:\n", df_mean)

# Check summary statistics again
df_mean.describe()

After Mean Imputation:
   Patient_ID        Age  Blood_Pressure Gender  Cholesterol
0         P1  25.000000           120.0      M      200.000
1         P2  30.000000           130.0      F      220.000
2         P3  29.285714           125.0      F      210.000
3         P4  22.000000           130.0      M      205.000
4         P5  40.000000           140.0    NaN      214.375
5         P6  29.285714           135.0      F      215.000
6         P7  29.000000           130.0      M      225.000
7         P8  31.000000           128.0      M      214.375
8         P9  28.000000           132.0    NaN      230.000
9        P10  29.285714           130.0      F      210.000

             Age  Blood_Pressure  Cholesterol
count  10.000000       10.000000    10.000000
mean   29.285714      130.000000   214.375000
std     4.611924        5.354126     8.955911
min    22.000000      120.000000   200.000000
25%    28.250000      128.500000   210.000000
50%    29.285714      130.000000   214.375000
75%    29.821429      131.500000   218.750000
max    40.000000      140.000000   230.000000

## Median Imputation

In [5]:
# Median Imputation
df_median = df.copy()

df_median.fillna({
    "Age": df["Age"].median(),
    "Blood_Pressure": df["Blood_Pressure"].median(),
    "Cholesterol": df["Cholesterol"].median()
}, inplace=True)

print("After Median Imputation:\n", df_median)
df_median.describe()

After Median Imputation:
   Patient_ID   Age  Blood_Pressure Gender  Cholesterol
0         P1  25.0           120.0      M        200.0
1         P2  30.0           130.0      F        220.0
2         P3  29.0           125.0      F        210.0
3         P4  22.0           130.0      M        205.0
4         P5  40.0           140.0    NaN        212.5
5         P6  29.0           135.0      F        215.0
6         P7  29.0           130.0      M        225.0
7         P8  31.0           128.0      M        212.5
8         P9  28.0           132.0    NaN        230.0
9        P10  29.0           130.0      F        210.0

             Age  Blood_Pressure  Cholesterol
count  10.000000       10.000000    10.000000
mean   29.200000      130.000000   214.000000
std     4.613988        5.354126     8.990736
min    22.000000      120.000000   200.000000
25%    28.250000      128.500000   210.000000
50%    29.000000      130.000000   212.500000
75%    29.750000      131.500000   218.750000
max    40.000000      140.000000   230.000000

## Mode Imputation

In [9]:
df_mode = df.copy()

df_mode.fillna({
    "Gender": df["Gender"].mode()[0]
}, inplace=True)

print("After Mode Imputation:\n", df_mode)
print("\nGender frequency counts after imputation:\n", df_mode["Gender"].value_counts())

After Mode Imputation:
   Patient_ID   Age  Blood_Pressure Gender  Cholesterol
0         P1  25.0           120.0      M        200.0
1         P2  30.0           130.0      F        220.0
2         P3   NaN           125.0      F        210.0
3         P4  22.0             NaN      M        205.0
4         P5  40.0           140.0      F          NaN
5         P6   NaN           135.0      F        215.0
6         P7  29.0             NaN      M        225.0
7         P8  31.0           128.0      M          NaN
8         P9  28.0           132.0      F        230.0
9        P10   NaN           130.0      F        210.0

Gender frequency counts after imputation:
 Gender
F    6
M    4
Name: count, dtype: int64